### ISSUE TITLE
Refactor to functional components

### ISSUE THREAD

**Issue by Kuboczoch** [chrissyast/band-repertoire#8]
Functional components are great and will help you implement #5 and will minimize a boilerplate from the old react

https://github.com/chrissyast/band-repertoire/blob/ab5ae3620c4b142fc956d6709b9e9edbec149da2/app/javascript/components/InputSection.js#L8-L67

**Comment by chrissyast** [comment]
@Kuboczoch these are issues which I have created for myself as reminders of work I plan to do. I'm not sure how you have found this repo and why you are commenting on it.

**Comment by Kuboczoch** [comment]
> @Kuboczoch these are issues which I have created for myself as reminders of work I plan to do. I'm not sure how you have found this repo and why you are commenting on it.

@chrissyast I'm just suggesting to use some features that can improve your code quality and readability. And I have found it on GitHub explore 😉

**Comment by chrissyast** [comment]
@Kuboczoch Thanks for your input :)
